### ISSUE TITLE
안녕하세요. 궁금한 점이 있어서 문의 드립니다.

### ISSUE THREAD

**Issue by Nanamare** [pplink/pagecall-android-sdk#1]
1. 미팅 나가기 기능이 인터페이스로 언제 제공될 예정일까요 ?
현재는
"미팅이 종료되었습니다. 탭을 종료해주세요."
클릭해야 `Android.onExit();` 이벤트가 발생하도록 처리되어 있는 것 같아 빠르게 해결하려면 라이브러리를 다운 받아 Android.onExit(); 를 원하는 시점에서 명시적으로 호출하는 수 밖에 없어 보입니다.

2. 동영상 플레이어가 보이는 복습하기에서 닫기 버튼이 눌리지 않아, "미팅이 종료되었습니다. 탭을 종료해주세요." 화면을 볼 수 없고 결과적으로 Android.onExit(); 이벤트를 발생시킬 수 없습니다.

답변 부탁드리겠습니다. 감사합니다 :)

**Comment by parkjurung** [comment]
안녕하세요! 관련 엔지니어에게 전달하여 늦어도 이번주 안으로는 답변드릴 수 있도록 하겠습니다.

**Comment by parkjurung** [comment]
슬랙으로 답변 완료하여 이슈 닫겠습니다 :)
